### ISSUE TITLE
Udisks2: Change SMART ID read as temperature

### ISSUE THREAD

**Issue by aretaon** [UshakovVasilii/gnome-shell-extension-freon#171]
I connected a newer Kingston SA400 SSD and Freon (with UDisks2 as temperature utility) reports 99 °C as temperature. For all other SSDs in the setup, temperature reporting works fine.

The same issue is visible in the screenshot shown in #167.

Using smartctl --all /dev/sda I get (some lines removed for clarity)

```ID# ATTRIBUTE_NAME          FLAG     VALUE WORST THRESH TYPE      UPDATED  WHEN_FAILED RAW_VALUE
194 Temperature_Celsius     0x0022   034   034   000    Old_age   Always       -       34 (Min/Max 23/34)
231 SSD_Life_Left           0x0000   099   099   000    Old_age   Offline      -       99
```
I assume that UDisks2 reports on SMART value 231 instead of 194 resulting in the unrealistic temperature read out.

For now I switched to hddtemp which works fine with the SSD but is there a way to change the SMART value that Freon reads from udisks2?

**Comment by corecontingency** [comment]
@aretaon This is an upsteam issue in `libatasmart` which udisks2 uses to read the temperate values.

Unfortunately, after making the library, Lennart Poettering moved on to bigger and better things, and upstream has been dead for over eight years. There are several outstanding patches for issues that no one has merged or looked at.

Here is the link for the bug report for this issue:
https://bugs.freedesktop.org/show_bug.cgi?id=97446

Luckily, this is one of the cases where the fix is simple and a patch has been made.
https://bugs.freedesktop.org/attachment.cgi?id=125967

So either compile and install libatasmart manually, or pester your distro maintainers to incorporate this patch.

**Comment by aretaon** [comment]
Thanks @corecontingency for your help. So far I decided to keep with the official Ubuntu Kernel and and hddtemp.
Anyway concerning Freon, I consider this issue closed.
