### ISSUE TITLE
Gnome 42?

### ISSUE THREAD

**Issue by techyporcupine** [UshakovVasilii/gnome-shell-extension-freon#230]
Can we get support for Gnome 42?
I am running fedora 36 with Gnome 42, and the extension is "outdated"

**Comment by JmbFountain** [comment]
I just checked, and the Extension seems to install fine by cloning the git repo and installing manually.

**Comment by retrixe** [comment]
Nonetheless, it would be a good idea to publish an update to https://extensions.gnome.org

**Comment by UshakovVasilii** [comment]
Done, under review

**Comment by UshakovVasilii** [comment]
Review failed:
> you cannot use `sudo` in extensions. You should use `pkexec` instead:
> https://gjs.guide/extensions/review-guidelines/review-guidelines.html#privileged-subprocess-must-not-be-user-writable

Related to #220

**Comment by techyporcupine** [comment]
You can manually install.

**Comment by Ud4ba** [comment]
> You can manually install.

Thanks.Will this get an update at https://extensions.gnome.org/ ?

**Comment by retrixe** [comment]
I think it would be a good idea to temporarily revert the ipmi-sensors support and publish the 42 release without it, because it looks like you need elevated privileges to read from ipmi-sensors, and for that you'd ideally need some sort of background daemon running as an elevated user from which you can query the sensor data as a regular user. This would be a bit involved to setup, and if not this, then you would need some way to configure ipmi-sensors data to be readable as non-root, so it might be advisable to revert the support for now and publish an update until a solution can be found.

**Comment by techyporcupine** [comment]
I agree with you @retrixe. I don't know how many people use `ipmi-sensors`, but if they truly need to, they can just clone from Github and install themselves.

**Comment by techyporcupine** [comment]
@UshakovVasilii Is it possible to remove `ipmi-sensors` support then publish the update?

**Comment by techyporcupine** [comment]
I would be willing to test the extension.

**Comment by Its-Alex** [comment]
I would be willing to test the extension too :slightly_smiling_face:.

**Comment by UshakovVasilii** [comment]
@techyporcupine @Its-Alex I created https://github.com/UshakovVasilii/gnome-shell-extension-freon/tree/without-ipmi branch, please test it

**Comment by techyporcupine** [comment]
Just installed. So far it seems to be working, I can keep using it for a while and see if it breaks.

**Comment by Ud4ba** [comment]
Thanks for the update works fine :)

**Comment by techyporcupine** [comment]
Been using it for about a day, seems to be stable.

**Comment by Its-Alex** [comment]
Tested on Archlinux that works 👍 Thanks for the update 🙏

**Comment by UshakovVasilii** [comment]
Approved on extensions.gnome.org
